theme: jekyll-theme-minimal
layout: default
logo: logo.jpeg
title: 'WSCC: Chess club in Bremerton/Port Orchard'
tagline: Chess club in Bremerton/Port Orchard
url: https://chessand.beer
description: "Chess club based out of Port Orchard and Bremerton, WA. All skill levels welcome!"
